name: Run unit tests
on:
  pull_request:
  push:
    branches: [main]
jobs:
  test_on_wasm:
    name: Build and Test on WebAssembly
    runs-on: Ubuntu-18.04
    container:
      image: ghcr.io/swiftwasm/carton:latest
    steps:
      - uses: actions/checkout@v2
      - run: carton test
  test_on_native:
    name: Build and Test on Native
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - run: swift test
  build:
    name: Build and Upload artifact
    runs-on: Ubuntu-18.04
    container:
      image: ghcr.io/swiftwasm/swift:5.3
    steps:
      - uses: actions/checkout@v2
      - run: apt update && apt install nodejs npm -y
      - name: Build
        run: npm ci && npm run build:prod
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
